# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUo83UfL1kCMpW969PBxthUcHEfzN9yJ

Assignment

Task 1 - Basic Operation
"""

# Taking two integer inputs from user
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

# Performing arithmetic operations
print(f"Addition: {num1 + num2}")
print(f"Subtraction: {num1 - num2}")
print(f"Multiplication: {num1 * num2}")

# Handling division safely
if num2 != 0:
    print(f"Division: {num1 / num2}")
    print(f"Modulus: {num1 % num2}")
else:
    print("Division and Modulus not possible (division by zero)")

print(f"Exponentiation: {num1 ** num2}")

"""Task 2 - Lists and Numpy"""

import numpy as np

# Creating a list with 10 numbers
numbers = [10, 25, 5, 40, 15, 60, 30, 20, 50, 35]

# Length of list
print("\nLength of list:", len(numbers))

# Max and Min
print("Maximum value:", max(numbers))
print("Minimum value:", min(numbers))

# Adding and removing element
numbers.append(70)
numbers.remove(5)

print("Updated List:", numbers)

# Sorting
print("Ascending Order:", sorted(numbers))
print("Descending Order:", sorted(numbers, reverse=True))

# Convert to NumPy array
arr = np.array(numbers)

# Calculations
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

"""Task 3 - Dictionaries and Sets"""

# Creating dictionary
student = {
    "name": "Saagar",
    "age": 18,
    "course": "Data Science",
    "marks": 85
}

# Printing key-value pairs
print("\nStudent Details:")
for key, value in student.items():
    print(f"{key} : {value}")

# Adding new key
student["grade"] = "A"
print("Updated Dictionary:", student)

# Creating set
courses = {"Python", "Data Science", "AI", "Python"}
print("Unique Courses:", courses)

# Set operations
set1 = {"Python", "AI", "ML"}
set2 = {"AI", "Data Science", "DL"}

print("Union:", set1.union(set2))
print("Intersection:", set1.intersection(set2))
print("Difference:", set1.difference(set2))

"""Task 4 - File Handling"""

# Writing to file
with open("student_data.txt", "w") as file:
    file.write("Rahul,Python,80\n")
    file.write("Anjali,Data Science,90\n")
    file.write("Ravi,AI,70\n")
    file.write("Sneha,ML,85\n")
    file.write("Kiran,DL,60\n")

# Reading file and filtering marks > 75
print("\nStudents with marks above 75:")

with open("student_data.txt", "r") as file:
    for line in file:
        name, course, marks = line.strip().split(",")
        if int(marks) > 75:
            print(f"{name} - {course} - {marks}")